# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/derek.d/irods/db_template_test/database

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/derek.d/irods/db_template_test/database

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek.d/irods/db_template_test/database/CMakeFiles /home/derek.d/irods/db_template_test/database//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derek.d/irods/db_template_test/database/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named all-plugins-database

# Build rule for target.
all-plugins-database: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all-plugins-database
.PHONY : all-plugins-database

# fast build rule for target.
all-plugins-database/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all-plugins-database.dir/build.make CMakeFiles/all-plugins-database.dir/build
.PHONY : all-plugins-database/fast

#=============================================================================
# Target rules for targets named irods_database_plugin-postgres

# Build rule for target.
irods_database_plugin-postgres: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irods_database_plugin-postgres
.PHONY : irods_database_plugin-postgres

# fast build rule for target.
irods_database_plugin-postgres/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/build
.PHONY : irods_database_plugin-postgres/fast

#=============================================================================
# Target rules for targets named IRODS_PHONY_TARGET_icatSysTables_postgres.sql

# Build rule for target.
IRODS_PHONY_TARGET_icatSysTables_postgres.sql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IRODS_PHONY_TARGET_icatSysTables_postgres.sql
.PHONY : IRODS_PHONY_TARGET_icatSysTables_postgres.sql

# fast build rule for target.
IRODS_PHONY_TARGET_icatSysTables_postgres.sql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_postgres.sql.dir/build.make CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_postgres.sql.dir/build
.PHONY : IRODS_PHONY_TARGET_icatSysTables_postgres.sql/fast

#=============================================================================
# Target rules for targets named irods_database_plugin-mysql

# Build rule for target.
irods_database_plugin-mysql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irods_database_plugin-mysql
.PHONY : irods_database_plugin-mysql

# fast build rule for target.
irods_database_plugin-mysql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/build
.PHONY : irods_database_plugin-mysql/fast

#=============================================================================
# Target rules for targets named IRODS_PHONY_TARGET_icatSysTables_mysql.sql

# Build rule for target.
IRODS_PHONY_TARGET_icatSysTables_mysql.sql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IRODS_PHONY_TARGET_icatSysTables_mysql.sql
.PHONY : IRODS_PHONY_TARGET_icatSysTables_mysql.sql

# fast build rule for target.
IRODS_PHONY_TARGET_icatSysTables_mysql.sql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_mysql.sql.dir/build.make CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_mysql.sql.dir/build
.PHONY : IRODS_PHONY_TARGET_icatSysTables_mysql.sql/fast

#=============================================================================
# Target rules for targets named irods_database_plugin-oracle

# Build rule for target.
irods_database_plugin-oracle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irods_database_plugin-oracle
.PHONY : irods_database_plugin-oracle

# fast build rule for target.
irods_database_plugin-oracle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/build
.PHONY : irods_database_plugin-oracle/fast

#=============================================================================
# Target rules for targets named IRODS_PHONY_TARGET_icatSysTables_oracle.sql

# Build rule for target.
IRODS_PHONY_TARGET_icatSysTables_oracle.sql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IRODS_PHONY_TARGET_icatSysTables_oracle.sql
.PHONY : IRODS_PHONY_TARGET_icatSysTables_oracle.sql

# fast build rule for target.
IRODS_PHONY_TARGET_icatSysTables_oracle.sql/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_oracle.sql.dir/build.make CMakeFiles/IRODS_PHONY_TARGET_icatSysTables_oracle.sql.dir/build
.PHONY : IRODS_PHONY_TARGET_icatSysTables_oracle.sql/fast

# target to build an object file
src/db_plugin.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/db_plugin.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/db_plugin.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/db_plugin.o
.PHONY : src/db_plugin.o

# target to preprocess a source file
src/db_plugin.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/db_plugin.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/db_plugin.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/db_plugin.i
.PHONY : src/db_plugin.i

# target to generate assembly for a file
src/db_plugin.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/db_plugin.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/db_plugin.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/db_plugin.s
.PHONY : src/db_plugin.s

# target to build an object file
src/general_query.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query.o
.PHONY : src/general_query.o

# target to preprocess a source file
src/general_query.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query.i
.PHONY : src/general_query.i

# target to generate assembly for a file
src/general_query.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query.s
.PHONY : src/general_query.s

# target to build an object file
src/general_query_setup.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query_setup.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query_setup.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query_setup.o
.PHONY : src/general_query_setup.o

# target to preprocess a source file
src/general_query_setup.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query_setup.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query_setup.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query_setup.i
.PHONY : src/general_query_setup.i

# target to generate assembly for a file
src/general_query_setup.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_query_setup.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_query_setup.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_query_setup.s
.PHONY : src/general_query_setup.s

# target to build an object file
src/general_update.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_update.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_update.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_update.o
.PHONY : src/general_update.o

# target to preprocess a source file
src/general_update.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_update.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_update.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_update.i
.PHONY : src/general_update.i

# target to generate assembly for a file
src/general_update.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/general_update.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/general_update.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/general_update.s
.PHONY : src/general_update.s

# target to build an object file
src/irods_catalog_properties.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_catalog_properties.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_catalog_properties.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_catalog_properties.o
.PHONY : src/irods_catalog_properties.o

# target to preprocess a source file
src/irods_catalog_properties.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_catalog_properties.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_catalog_properties.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_catalog_properties.i
.PHONY : src/irods_catalog_properties.i

# target to generate assembly for a file
src/irods_catalog_properties.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_catalog_properties.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_catalog_properties.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_catalog_properties.s
.PHONY : src/irods_catalog_properties.s

# target to build an object file
src/irods_sql_logger.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_sql_logger.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_sql_logger.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_sql_logger.o
.PHONY : src/irods_sql_logger.o

# target to preprocess a source file
src/irods_sql_logger.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_sql_logger.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_sql_logger.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_sql_logger.i
.PHONY : src/irods_sql_logger.i

# target to generate assembly for a file
src/irods_sql_logger.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/irods_sql_logger.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/irods_sql_logger.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/irods_sql_logger.s
.PHONY : src/irods_sql_logger.s

# target to build an object file
src/low_level_odbc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/low_level_odbc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/low_level_odbc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/low_level_odbc.o
.PHONY : src/low_level_odbc.o

# target to preprocess a source file
src/low_level_odbc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/low_level_odbc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/low_level_odbc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/low_level_odbc.i
.PHONY : src/low_level_odbc.i

# target to generate assembly for a file
src/low_level_odbc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/low_level_odbc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/low_level_odbc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/low_level_odbc.s
.PHONY : src/low_level_odbc.s

# target to build an object file
src/mid_level_routines.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/mid_level_routines.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/mid_level_routines.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/mid_level_routines.o
.PHONY : src/mid_level_routines.o

# target to preprocess a source file
src/mid_level_routines.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/mid_level_routines.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/mid_level_routines.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/mid_level_routines.i
.PHONY : src/mid_level_routines.i

# target to generate assembly for a file
src/mid_level_routines.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-postgres.dir/build.make CMakeFiles/irods_database_plugin-postgres.dir/src/mid_level_routines.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-mysql.dir/build.make CMakeFiles/irods_database_plugin-mysql.dir/src/mid_level_routines.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irods_database_plugin-oracle.dir/build.make CMakeFiles/irods_database_plugin-oracle.dir/src/mid_level_routines.s
.PHONY : src/mid_level_routines.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... IRODS_PHONY_TARGET_icatSysTables_mysql.sql"
	@echo "... IRODS_PHONY_TARGET_icatSysTables_oracle.sql"
	@echo "... IRODS_PHONY_TARGET_icatSysTables_postgres.sql"
	@echo "... all-plugins-database"
	@echo "... irods_database_plugin-mysql"
	@echo "... irods_database_plugin-oracle"
	@echo "... irods_database_plugin-postgres"
	@echo "... src/db_plugin.o"
	@echo "... src/db_plugin.i"
	@echo "... src/db_plugin.s"
	@echo "... src/general_query.o"
	@echo "... src/general_query.i"
	@echo "... src/general_query.s"
	@echo "... src/general_query_setup.o"
	@echo "... src/general_query_setup.i"
	@echo "... src/general_query_setup.s"
	@echo "... src/general_update.o"
	@echo "... src/general_update.i"
	@echo "... src/general_update.s"
	@echo "... src/irods_catalog_properties.o"
	@echo "... src/irods_catalog_properties.i"
	@echo "... src/irods_catalog_properties.s"
	@echo "... src/irods_sql_logger.o"
	@echo "... src/irods_sql_logger.i"
	@echo "... src/irods_sql_logger.s"
	@echo "... src/low_level_odbc.o"
	@echo "... src/low_level_odbc.i"
	@echo "... src/low_level_odbc.s"
	@echo "... src/mid_level_routines.o"
	@echo "... src/mid_level_routines.i"
	@echo "... src/mid_level_routines.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

